### ISSUE TITLE
Site: phone.app - certificate expired on 11/10/2021

### ISSUE THREAD

**Issue by jayrope** [victordiaz/PHONK#109]
Just FYI: https://phonk.app/ neds new certificate.

**Comment by 42loop** [comment]
Just FYI: https://phonk.app is now offline

**Comment by polhomarkho** [comment]
https://phonk.app/ seems to be up and has a valid certificate 🎉
glad to see it's not dead 😊

**Comment by victordiaz** [comment]
Thanks all for this, I've been a bit busy catching up with life and family so did not have much time for PHONK. But I'm trying catch up now :)
