### ISSUE TITLE
Is it possible in PHONK to create a transparent widget that hovers over other activities ...

### ISSUE THREAD

**Issue by gtusr** [victordiaz/PHONK#129]
... and does not cover the entire screen, where different actions have been assigned to different regions of the widget?

On a more general note, does PHONK support building up activities from fragments, defining and running content service providers, broadcast receivers, and background services for full-suite Android application development?

The project's website and the remote IDE interface are nice touches, but I'm still left wondering, after reading the reference documentation, how fully this platform can replace traditional app develop inside Android studio leveraging features in the latest SDK.

**Comment by victordiaz** [comment]
Hi @gtusr 
I think that what you are trying to achieve is not possible with PHONK.

PHONK is a different tool than Android Studio + Android SDK and it does not focus on creating full complex apps. If you want to do complex stuff I recommend you to use the normal path to develop apps.
