### ISSUE TITLE
Widget TextList: text size doesn't apply

### ISSUE THREAD

**Issue by notEvil** [victordiaz/PHONK#137]
Hi,

```javascript
var text_list = ui.addTextList(0, 0, 1, 1)
text_list.textSize(10)
text_list.autoScroll(true)


var count = 0

util.loop(1000, () => {
  text_list.add((count++).toString())
}).start()
```

gives me

<img src="https://user-images.githubusercontent.com/4567628/221136971-b281f578-1e38-4198-829e-3de86d16d281.png" height="400px"/>

All lines except one are using the default text size. It is semi random which line is using the correct text size. I have no clue why; an implementation based on List works as expected, see https://gitlab.com/notEvil/cyclometer/-/blob/master/PHONK/app/lib/mui.js.

**Comment by victordiaz** [comment]
oh! I will have a look.
I allocated time next week to do some PHONK work.

By the way, feel free to join the Discord channel in case you wanna have a chat there!

**Comment by notEvil** [comment]
fixed in https://github.com/victordiaz/PHONK/pull/141
