### ISSUE TITLE
title in buttons is not displayed

### ISSUE THREAD

**Issue by boriskohen** [victordiaz/PHONK#21]
it's appears only on devices with kitkat (android 4.4).
affected 1.2.0 and 1.2.2 versions. affected installation wizard and projects view.
![Screenshot_2020-06-29-15-57-47](https://user-images.githubusercontent.com/60200260/86003337-4a7f6380-ba1a-11ea-8351-cf66072937bc.png)

**Comment by victordiaz** [comment]
Oh! thats interesting, I will have a look today.
What is the screen size? I will try to replicate it with an emulator

**Comment by boriskohen** [comment]
320x480px  
3" size

**Comment by victordiaz** [comment]
Hi @boriskohen

I think I fixed it, it seems that Android 4.4 didn't pick the "backgroundTint" property, so I changed to the standard "background"
I will do a new release this week with the changes

I will let you know when the new version is online so you can double check and close the issue

Thanks for pointing it out!

**Comment by tinkercnc** [comment]
Same behavior on:
device
    type: phone
    manufacturer: OnePlus
    model name: A0001

screen
    brightness: 93
    screen: true
    orientation: portrait
    screen dpi: 480
    screen resolution: 1080 x 1920

Cyanogen OS
Android 4.4.4 

Just FYI.

**Comment by garydion** [comment]
I can also confirm it occurs on an Alcatel OneTouch running 4.4.4.  Additionally, the proceed buttons during installation were invisible.  These were the ones which were to say "Let's Go", "Ask Permissions", and "Install Examples".  But thanks to your "Getting Started" guide on the website, I knew where to tap.  Despite the bug, I'm already having a blast!

**Comment by victordiaz** [comment]
I just uploaded a new version, cand you check if buttons appear now? thanks :)

**Comment by tinkercnc** [comment]
> I just uploaded a new version, cand you check if buttons appear now? thanks :)

Nope, for instance the    
Phonk Example Device info shows this:

![Screenshot_2020-07-03-15-03-08](https://user-images.githubusercontent.com/5290721/86472095-e53fb100-bd3e-11ea-8cd3-a6917b452ab7.png)

**Comment by garydion** [comment]
I can confirm that the buttons now display correctly during install.  Though like tinkercnc, my application buttons are still all white like in his screen shot.

**Comment by victordiaz** [comment]
Ok, it seems that there is something wrong :)
I have a device with 4.2 and dont get that problem :/ 
I'll have a deeper look tonight with the emulator

Thanks for checking

**Comment by victordiaz** [comment]
I think I found the problem. Apparently devices < 5.0 don't like background with transparencies. So I made a small hack to use a color shader on Androids lower than 5.0

I uploaded a version here
[https://github.com/victordiaz/PHONK/releases/tag/1.2.4](https://github.com/victordiaz/PHONK/releases/tag/1.2.4)

Could you check it? Thanks :)

**Comment by tinkercnc** [comment]
Yeah! 
Yes it's working!
Great piece of software!

Thanks a lot!

**Comment by boriskohen** [comment]
Thank you. It's working now. Great piece of software!

**Comment by garydion** [comment]
Yep, fixed on my phone too.  The buttons looks great.  Thanks!
