### ISSUE TITLE
Typo in Settings option

### ISSUE THREAD

**Issue by nickmartin1ee7** [victordiaz/PHONK#28]
In-App Settings show "hided" instead of "hidden"

1. Launch mobile app
2. Navigate to Settings
3. Under "Mask the Web Editor address" -> "The IP address will be **hided** as..."

![image](https://user-images.githubusercontent.com/58752614/86386035-35474680-bc5f-11ea-97bc-fe3cdd5c7022.png)

**Comment by victordiaz** [comment]
thx for pointing it out @nickmartin1ee7 
I'll fix it asap :)
Do not hesitate sending more typos, grammar or other type of errors in the app.

Much appreciated

**Comment by victordiaz** [comment]
its fixed in 1.2.3 already :)
