### ISSUE TITLE
Util.parseBytes only supports chars

### ISSUE THREAD

**Issue by txf-** [victordiaz/PHONK#46]
```
    public Object parseBytes(byte[] bytes, String type) {
        BluetoothBytesParser parser = new BluetoothBytesParser(bytes);

        switch (type) {
            case "uint8":
                return parser.getIntValue(BluetoothBytesParser.FORMAT_UINT8);
            case "string":
                return parser.getStringValue(0);
            default:
                return null;
        }
    }
```
Ideally this section in PUtil.java should support more datatypes than just 8 bit values. Presumably BluetoothBytesParser supports more data types?

**Comment by victordiaz** [comment]
@txf- 
It seems to support float, int and longs as far as a I can see. I will include them and release it in the next version.
Thanks for commenting on this

**Comment by victordiaz** [comment]
I included some more data types although I only managed to test uint8 and strings. For some reason float does not work for me but maybe I'm just sending wrongly the data from my ESP

**Comment by victordiaz** [comment]
Hi @txf- 
The new version is online with the changes.
Let me know if that works as intented

Thanks

**Comment by victordiaz** [comment]
I close the issue since I think a previous commit improved the situation :)
