### ISSUE TITLE
No Permission to send SMS, smsSend()

### ISSUE THREAD

**Issue by Nic7C5** [victordiaz/PHONK#47]
I appreiciate your work. It's very handy for beginners.

When trying the SMS function I faced an error.

Blackberry Key 2 (BBF100-6)
Android 8.1.0 (Kernel 4.4.78...) Security Patch May 2020
Phonk Version 1.2.5 normal / extended (from github, tried both versions)

calling the function 
`smsSend(012345,'test')`

throws the error `Wrapped java.lang.SecurityExeption: Sending SMS message: uid 10238 does not have andoird.permissionSEND_SMS.`

 [https://support.google.com/googleplay/android-developer/answer/9047303?hl=en](https://support.google.com/googleplay/android-developer/answer/9047303?hl=en)

I granted all permissions Phonk asked for. The android settings menu says that the app has permission to send SMS.
![Screenshot_20200708-105759](https://user-images.githubusercontent.com/22579228/86899327-29013480-c10a-11ea-9aee-7aba9ed57580.png)

**Comment by victordiaz** [comment]
Hello @Nic7C5 

Google Play does not allow anymore apps that access the SMS, so for that reason I created a separated extended APK that you have to download from here [https://github.com/victordiaz/PHONK/releases/tag/1.2.5](https://github.com/victordiaz/PHONK/releases/tag/1.2.5)

Can you try to install that version and let me know if it works? (you have to uninstall the previous version)

**Comment by Nic7C5** [comment]
I just updated my first post. At first I used version 1.2.5 from the Playstore. Now I installed the 1.2.5 extended apk from here. The error is still the same.

**Comment by victordiaz** [comment]
Ok I see, I'll have a look later with more detail and see what's going on :)
Thanks for reporting

**Comment by victordiaz** [comment]
Hello @Nic7C5 

Could you check to install `phonk-1.2.6-alpha-4-extended-release.apk` from [https://github.com/victordiaz/PHONK/releases/tag/1.2.6-alpha](https://github.com/victordiaz/PHONK/releases/tag/1.2.6-alpha) and tell me if it works for you?

Thanks

**Comment by victordiaz** [comment]
@Nic7C5 
One thing I saw in your first comment the method `device.smsSend(012345 , 'test')` should be instead `device. smsSend('012345', 'test')` 
The number is a string since you can write Phone numbers with the + prefix

**Comment by Nic7C5** [comment]
It's working with the alpha 4 (and number as string). Thanks!

**Comment by victordiaz** [comment]
I will keep the issue open until the next release. Thanks for testing it :)

**Comment by victordiaz** [comment]
The new version is online with the changes.
Feel free to close the issue if everything works fine for you :)

**Comment by adasq** [comment]
When can we expect this version to be published into Google Play Store?

**Comment by victordiaz** [comment]
Hi @adasq 
Google Play is nowadays very strict with some features like sending SMS, so if you are not a big company or your SMS sending is justified somehow they don't allow it.
For that reason there is an Extended version [https://github.com/victordiaz/PHONK/releases](https://github.com/victordiaz/PHONK/releases) here that you can download and install in your phone or tablet that has SMS functionality.

I hope it works for you! Let me know if it does not.

**Comment by adasq** [comment]
Hey @victordiaz,

Thanks for the response. I tried the released APK, but unfortunately, it crashes after downloading examples.

**Comment by victordiaz** [comment]
@adasq try to uninstall all the PHONK versions in your phone and then reinstall the extended version. Let me know if that works!

**Comment by adasq** [comment]
Well, it works!
Really appreciate your work. Thank you.
