### ISSUE TITLE
LiveCodingOverlay has small font size 

### ISSUE THREAD

**Issue by victordiaz** [victordiaz/PHONK#49]
**Problem description**
As reported in #32 
example Advanced / LiveCoding : when pressing Ctrl+Shift+X from the Web Editor, there is a very tiny unreadable line of text displayed temporarily at the bottom of the application on the tablet.

**Device model**
Acer Iconia B1-A71 tablet

**Android version**
Android 4.1.2. 

**Steps to reproduce the bug**

**Comment by SuperUserNameMan** [comment]
I've just found the tiny text that appears at the bottom of the tablet (when pressing Ctrl + Return) is a copy of the code-line that is updated.

It is still very tiny and unreadable with 1.2.7

**Comment by victordiaz** [comment]
Hi, I forgot to update the example :) I just changed it. 

In the code itself you can change the size using
``` .textSize(12)```

I will include the change in the next release
Thanks :)

**Comment by victordiaz** [comment]
By the way, the liveCoding thing is just a way to show people what line is executed in each time. It's a bit geeky buy found it useful for demonstration purposes :)

**Comment by victordiaz** [comment]
@SuperUserNameMan The example is adjusted in 1.2.8 so the text looks a bit bigger. Feel free to close it after you try it :)

**Comment by SuperUserNameMan** [comment]
@victordiaz : yes it's better.

> Feel free to close it after you try it :)

PS : i can't close issues if that what you meant.

**Comment by victordiaz** [comment]
Thx, for checking. I realized I opened the issue :facepalm:  I close it :smile:
