### ISSUE TITLE
app console has small font size

### ISSUE THREAD

**Issue by victordiaz** [victordiaz/PHONK#50]
**Problem description**
As reported in #32 
The text into the kind of error box is very small an almost unreadable (but i've just noticed they appear into the Console box of the WebEditor too).

**Device model**
Acer Iconia B1-A71 tablet

**Android version**
Android 4.1.2. 

**Steps to reproduce the bug**

**Comment by victordiaz** [comment]
@SuperUserNameMan could you send me an screenshot?

**Comment by SuperUserNameMan** [comment]
Note : The Display / Font Size parameter of my tablet is set to "Normal". 
The actual width of the screen is 9cm and its diagonal is 7 inches.

![Screenshot_2020-07-12-15-23-23](https://user-images.githubusercontent.com/9801802/87247384-d8644100-c453-11ea-870d-155d3584d566.png)

**Comment by victordiaz** [comment]
@SuperUserNameMan I increased tiny bit the default console size. Do you think is enough or should I have a bigger text size for tablets?

**Comment by SuperUserNameMan** [comment]
Oh I forgot to keep you updated with this change when testing new version yesterday. sorry.

Yes, now it has same size as the text at the top. It is readable.

You can close this issue :-)

**Comment by victordiaz** [comment]
Perfect, thx :)
