### ISSUE TITLE
OpenStreetMaps do not work on Android 4.x.x

### ISSUE THREAD

**Issue by victordiaz** [victordiaz/PHONK#53]
**Problem description**
As mentioned in #32 
example GUI / Maps (OpenStreetMaps) : It does not display any map. The background is a gray grid with a "MAPS (OPENSTREEMAPS)" title in bold yellow, a red circle, a cyan circle, two blue segments and a pinpoint-location icone. Zooming and scrolling moves them randomly.

**Device model**
Acer Iconia B1-A71

**Android version**
4.1.2

**Steps to reproduce the bug**

**Comment by victordiaz** [comment]
I had a look on other Android 4.x.x devices and it seems there is a problem with the OSM library PHONK is using.
I opened an issued here and see if there is some answer. [https://github.com/osmdroid/osmdroid/issues/1617](https://github.com/osmdroid/osmdroid/issues/1617)

**Comment by victordiaz** [comment]
@SuperUserNameMan

**Comment by victordiaz** [comment]
@SuperUserNameMan In the new version 1.2.8 maps should work correctly on 4.x.x device. Could you try it out? Thanks!

**Comment by SuperUserNameMan** [comment]
@victordiaz : Yes, I confirm it works ! :-D

**Comment by victordiaz** [comment]
Ok! thx for checking @SuperUserNameMan ! I close the issue then :smile:
