### ISSUE TITLE
LeakCanary?

### ISSUE THREAD

**Issue by marclava** [victordiaz/PHONK#58]
When compiled as a debug version (when using Android Studio), Phonks include LeakCanary to catch and report memory leaks.

Would it be useful to share LeakCanary reports? Is so, how?...

**Comment by victordiaz** [comment]
Hi @marclava 
I included LeakCanary because there is actually a memory leak in the main app that has to be fixed, is it in my TODO but a bit down in the list since is not very crucial.
You could just create an issue for each individual one

**Comment by victordiaz** [comment]
I think the memory leak should not be present any more, so I close this issue. LeakCanary though is still include it in PHONK as a way to see potential problems
