### ISSUE TITLE
Phone: toggleAirplaneMode

### ISSUE THREAD

**Issue by Krugergit** [victordiaz/PHONK#63]
Turning Airplane Mode on/off

**Comment by victordiaz** [comment]
Hi @Krugergit 
There is no way in Android to turn on the airplane mode on/off 

If you root your device you could execute some shell code as explained in the first answer in this StackOverflow question 
[https://stackoverflow.com/questions/13766909/how-to-programmatically-enable-and-disable-flight-mode-on-android-4-2](https://stackoverflow.com/questions/13766909/how-to-programmatically-enable-and-disable-flight-mode-on-android-4-2)
