### ISSUE TITLE
Looper.speed() doesn't reset if it has expired after setting a new value

### ISSUE THREAD

**Issue by Ulugbeg** [victordiaz/PHONK#79]
Looking at the sourcecode at https://github.com/victordiaz/phonk/blob/master/phonk_apprunner/src/main/java/io/phonk/runner/apprunner/api/other/PLooper.java#L85-L86:

```java
        this.speed = duration;
        if (duration < this.speed) {
```

It seems as if this code doesn't do what it's intended to do; the condition on line 86 will never be true due to, well, line 85 :)

Love the project!

**Comment by victordiaz** [comment]
Hi @Ulugbeg 
I really don't know what I was thinking when I wrote that code :) Fixing it ASAP. 

Thanks!

**Comment by victordiaz** [comment]
I think this issue was resolved, please feel free to reopen it the problem still exists :)
